### PR TITLE
Pictogram page

### LINKED ISSUE #159: Improvement - Margin between introduction text and text field
**Describe current situation**  
_The margin between the introduction text and text field is too small._

**Describe the improvement**  
_Change the margin to $spacing-layout-48._

**Screenshot**
pictograms-spacing-text

**Additional context**  
_https://deploy-preview-156--digitaldesign.netlify.app/foundation/pictograms/pictograms._

### PR DESCRIPTION
**Pull request by mmexvr**
**Describe pull-request**  
_Describe what the pull-request is about_

- Design for pictogram
- Fix first level pages not showing lead text
- Commented out last update lastupdaterender function
- Fix for code example template, incorrect col classes in tab-content

**Solving issue**  
_Add which issue this pull-request solves by adding # plus the number of the issue (for example #123)_
Fixes: #155, Pictogram page

Feedback:
Fixes: #157
Fixes: #158
Fixes #159
Fixes: #161
Fixes: #172 
Does not fix fully, just the bug in safari #160 (Temp) should have 2px on bottom when focused

**How to test**  
_Add description how to test if possible_
- Go to pictogram page

**Additional context**  
_Add any other context about the pull-request here._

Checkboxes are not done, Q1

### CODE REVIEW

**Review by niklasros — COMMENTED** [review]
See issues #157 #158 #159 #160 #161 #162

**Comment by mmexvr** [comment]
Fixed: #161 #157 #159

**Comment by mmexvr** [comment]
Fixed: #158

**Comment by niklasros** [comment]
The text and button is mis-aligned.

_Implementation_
download-bar-site

_Design reference_
download-bar-figma

**Comment by mmexvr** [comment]
Padding fixed!

**Review by niklasros — APPROVED** [review]

**Review by helloimela — APPROVED** [review]
Looks good!

**Pull request merged**
