### PR TITLE
Improvement - landing page 

### PR DESCRIPTION
**Pull request by helloimela**
**Describe pull-request**  
Landing page added.

**How to test**  
- See figma >> Landing page
- See in different breakpoints

### CODE REVIEW

**Comment by niklasros** [comment]
Make the entire card (including the image) clickable. Currently only the white container is a link.

**Comment by niklasros** [comment]
The Introduction text as well as Resources text should be aligned with the grid.

landing-alignment-mobile

**Comment by niklasros** [comment]
**Cards**
- The Medium card need to be smaller in height on mobile (Figma = 248px height).
- Can we make the image-container for the smaller cards a bit bigger in height on mobile to avoid the big cropping? In Figma I've used 232px height.
- The bigger card used for Media Bank need to have another size on mobile. Compare the implementation with the solution in Figma.
landing-card-3



landing-card-1


landing-card-2

**Comment by niklasros** [comment]
The video/image hero should get a portrait format on smaller screens.

landing-intro-mobile

**Review by mmexvr — APPROVED** [review]

**Comment by niklasros** [comment]
The spacing between the last card and the resource text should be $spacing-layout-128.

landing-spacing-mobile

**Review by niklasros — APPROVED** [review]

**Pull request merged**
